Repository EDCD/EDDN, pull requests merged in 2022-01, with the labels that each got.

#159 Address `bottle` default request size rejecting some messages
  src/eddn/Gateway.py
Labels: enhancement

#160 docs: Possible server responses, and handling them
  schemas/README-EDDN-schemas.md
Labels: documentation

#162 Gateway: Properly report all errors to uploaders
  schemas/README-EDDN-schemas.md
  scripts/testing/gateway-responses/Market.json
  scripts/testing/gateway-responses/README.md
  scripts/testing/gateway-responses/commodity-outdated-schema.json
  scripts/testing/gateway-responses/commodity-too-large.json
  scripts/testing/gateway-responses/market.json-to-schema.py
  scripts/testing/gateway-responses/scan-invalid-JSON.json
  scripts/testing/gateway-responses/scan-invalid-no-softwarename.json
  scripts/testing/gateway-responses/scan-invalid-no-starpos.json
  scripts/testing/gateway-responses/scan-valid.json
  scripts/testing/gateway-responses/test-bad-gzip.py
  scripts/testing/gateway-responses/test-bad-gzip.sh
  scripts/testing/gateway-responses/test-gzip-bad-formdata.py
  scripts/testing/gateway-responses/test-gzip-correct-formdata.py
  scripts/testing/gateway-responses/test-plain-bad-formdata.py
  scripts/testing/gateway-responses/test-plain-correct-formdata.py
  scripts/testing/gateway-responses/test-sender.py
  src/eddn/Gateway.py
Labels: enhancement, python

#169 Support `--loglevel <level>` CL arg in all entry point scripts
  src/eddn/Bouncer.py
  src/eddn/Gateway.py
  src/eddn/Monitor.py
  src/eddn/Relay.py
  src/eddn/conf/Settings.py
Labels: enhancement

#175 Add Approachsettlement
  schemas/approachsettlement-README.md
  schemas/approachsettlement-v1.0.json
  src/eddn/conf/Settings.py
Labels: enhancement

#174 Add FSSAllBodiesFound
  schemas/fssallbodiesfound-README.md
  schemas/fssallbodiesfound-v1.0.json
  src/eddn/conf/Settings.py
Labels: enhancement

#178 Flesh out doc/Contributing.md & other misc doc edits
  README.md
  contrib/monitor/index.html
  contrib/monitor/schemas.html
  contrib/test-schema.py
  docs/Adding-A-New-Schema.md
  docs/Contributing.md
  docs/Developers.md
  schemas/README-EDDN-schemas.md
  schemas/TEMPLATES/journalevent-README.md
  schemas/TEMPLATES/journalevent-v1.0.json
  schemas/approachsettlement-README.md
  schemas/blackmarket-README.md
  schemas/blackmarket-v1.0.json
  schemas/codexentry-README.md
  schemas/commodity-README.md
  schemas/commodity-v3.0.json
  schemas/fssallbodiesfound-README.md
  schemas/fssallbodiesfound-v1.0.json
  schemas/fssdiscoveryscan-README.md
  schemas/fssdiscoveryscan-v1.0.json
  schemas/navbeaconscan-README.md
  schemas/navbeaconscan-v1.0.json
  schemas/navroute-README.md
  schemas/outfitting-README.md
  schemas/outfitting-v2.0.json
  schemas/scanbarycentre-README.md
  schemas/scanbarycentre-v1.0.json
  schemas/shipyard-README.md
  schemas/shipyard-v2.0.json
  scripts/testing/gateway-responses/codexentry.json
Labels: documentation
